DROP DATABASE IF EXISTS BDD_USUARIOS_IVANG;
CREATE DATABASE BDD_USUARIOS_IVANG;
USE BDD_USUARIOS_IVANG;

CREATE TABLE T_USUARIOS (
    NICK_USUARIO VARCHAR(15) NOT NULL,
    CONTRASENYA INTEGER(5) NOT NULL
);

ALTER TABLE T_USUARIOS ADD PRIMARY KEY( NICK_USUARIO );

INSERT INTO T_USUARIOS VALUES('IVANGC', '12345');
INSERT INTO T_USUARIOS VALUES('ESTEBANMM', '23456');
INSERT INTO T_USUARIOS VALUES('PEPEHH', '34567');
INSERT INTO T_USUARIOS VALUES('CLAUDIAFF', '45678');
INSERT INTO T_USUARIOS VALUES('RODRIPL', '56789');